import turtle

wn=turtle.Screen()

turtle.pencolor('red')
turtle.forward(50)
turtle. left (45)
turtle.pencolor('orange')
turtle.forward(50)
turtle.left(45)
turtle.pencolor('green')
turtle.forward(50)
turtle.left(45)
turtle.pencolor('blue')
turtle.forward(50)
turtle. left (45)
turtle.pencolor('red')
turtle.forward(50)
turtle.left(45)
turtle.pencolor('orange')
turtle.forward(50)
turtle.left(45)
turtle.pencolor('green')
turtle.forward(50)
turtle.left(45)
turtle.pencolor('blue')
turtle.forward(50)

wn.mainloop()